#!/usr/bin/env zsh
# Disable xtrace as it would mangle the output.
builtin setopt local_options no_xtrace typeset_silent

((!${__quiet__:=0})) && log-line --color yellow --decor '⚠' --decor-bold "$@"
