#!/usr/bin/env zsh
# Disable xtrace as it would mangle the output.
setopt localoptions noxtrace

zparseopts -D -E -- -no-exit=no_exit p=__print__ -print=__print__ l=__line__ -line=__line__

log_cmd=( log-info )
[[ "$__print__" ]] && log_cmd=( log-print )
[[ "$__line__" ]] && log_cmd=( log-line )

trap 'finish $$ $?' EXIT
function finish() {
  _pid=$1
  _exit_code=$2
  if [[ -z "$no_exit" ]] {
    local log_cmd_args
    if (( !! _exit_code )) {
      log_cmd_args=( --color 'red' )
    }
    $log_cmd $log_cmd_args --arrow "    < $_pid" "$_exit_code"
  }
  return $_exit_code
}

$log_cmd --arrow "  ==> $$" "'${(q)${(q)@}}\'"
if (( $+functions[unset-stacktrace] )) { [[ "$@" == "brex-"* ]] || unset-stacktrace }
"$@"
