#!/usr/bin/env zsh
# Disable xtrace as it would mangle the output.
builtin setopt local_options no_xtrace typeset_silent

((!${__quiet__:=0} && ${__debug__:=0} || ${__info__:=0} || ${__verbose__:=0} >= 1 || ${__print__:=0})) && \
  log-line --color white --decor 'ℹ' "$@" || true
