#!/usr/bin/env zsh
# Disable xtrace as it would mangle the output.
builtin setopt local_options no_xtrace typeset_silent

function log-time() {
  ((!\
  ${__quiet__:=0} && \
  ${__debug__:=0} || \
  ${__verbose__:=0} >= 1 || \
  ${__print__:=0})) &&
    time $@ || $@
}
