#!/usr/bin/env zsh
# Disable xtrace as it would mangle the output.
builtin setopt local_options no_xtrace typeset_silent

if [[ "$1" =~ "[0-9]+" ]] { __exit_status__=$1 ; shift } else { __exit_status__=1 }
if (( $__exit_status__ == 0 )) {
  cmd=(--info)
  log-info "$@"
} else {
  log-debug "[${functrace}]"
  log-error "$@"
  log-debug "  > status: $__exit_status__"
}

(( $SHLVL >= 2 )) && exit $__exit_status__ || kill -INT $$
