#!/usr/bin/env zsh
# Disable xtrace as it would mangle the output.
builtin setopt local_options no_xtrace typeset_silent

if ((!${__quiet__:=0} && (${__debug__:-0} || ${__debug__[1]:-0} || ${__verbose__:=0} >= 2))); then
  log-line --color grey --decor '▶' "$@"
fi
