#!/usr/bin/env zsh
# Disable xtrace as it would mangle the output.
builtin setopt local_options no_xtrace typeset_silent

log-line --bold --color 'green' --arrow '====>' --arrow-bold --decor '⭑' --decor-color 'yellow' "$@"
